DROP TABLE IF EXISTS game;

CREATE TABLE game
(
    id   BIGINT PRIMARY KEY,
    pos  INT,
    time BIGINT,
    date DATE
);

CREATE TABLE USER (
    id BIGINT PRIMARY KEY,
    USERNAME VARCHAR (255),
    PASSWORD VARCHAR (255)
);
